[tool.bumpversion]
current_version = "0.5.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = true
sign_tags = false
tag_name = "python-{new_version}"
tag_message = "[release] python {current_version} → {new_version}"
allow_dirty = false
commit = true
message = "[release] python {current_version} → {new_version}"
commit_args = ""

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = "{current_version}"
replace = "{new_version}"

[[tool.bumpversion.files]]
filename = "src/saucelabs_visual/client.py"
search = "PKG_VERSION = '{current_version}'"
replace = "PKG_VERSION = '{new_version}'"
