using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SauceLabs.Visual.CodeGenerators
{
    [Generator]
    public class ExplicitValueSetGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput((i) =>
            i.AddSource("ExplicitValueSetAttribute.g.cs", @"namespace SauceLabs.Visual.CodeGenerators {
    ///<summary>
    /// Generates the following code for a field:
    /// 
    /// <code>
    /// private bool {fieldName}Set = false;
    /// 
    /// public {type} {PascalCase(fieldName)} 
    /// {
    ///     get => {fieldName},
    ///     set
    ///     {
    ///         {fieldName} = value;
    ///         {fieldName}Set = true;
    ///     }
    /// }
    /// 
    /// public void Unset{PascalCase(fieldName)}()
    /// {
    ///     {fieldName} = default;
    ///     {fieldName}Set = false;
    /// }
    /// </code>
    ///</summary> 
    [System.AttributeUsage(System.AttributeTargets.Field)]
    internal class ExplicitValueSetAttribute : System.Attribute { }
}"));

            // Find all field declarations with the ExplicitValueSet attribute
            var fieldDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (s, _) => s is FieldDeclarationSyntax syntax && syntax.AttributeLists.Count > 0,
                    transform: (ctx, _) => GetFieldSymbol(ctx))
                .Where(m => m is not null);

            // Generate
            context.RegisterSourceOutput(fieldDeclarations, (spc, source) => Execute(spc, source!));
        }

        private static IFieldSymbol? GetFieldSymbol(GeneratorSyntaxContext context)
        {
            var fieldDeclaration = (FieldDeclarationSyntax)context.Node;
            foreach (var variable in fieldDeclaration.Declaration.Variables)
            {
                if (context.SemanticModel.GetDeclaredSymbol(variable) is IFieldSymbol symbol &&
                    symbol.GetAttributes().Any(a => a.AttributeClass?.Name == "ExplicitValueSetAttribute"))
                {
                    return symbol;
                }
            }
            return null;
        }

        private static void Execute(SourceProductionContext context, IFieldSymbol symbol)
        {
            var classSymbol = symbol.ContainingType;
            var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
            var className = classSymbol.Name;

            var fieldName = symbol.Name;
            var fieldType = symbol.Type.ToDisplayString();

            // Create names: Value -> _value and _valueSet
            var propName = fieldName.TrimStart('_');
            propName = char.ToUpper(propName[0]) + propName.Substring(1);
            var flagName = $"{fieldName}Set";

            var source = $@"// <auto-generated/>
using System;

namespace {namespaceName}
{{
    partial class {className}
    {{
        private bool {flagName} = false;

        public {fieldType} {propName}
        {{
            get => {fieldName};
            set
            {{
                {fieldName} = value;
                {flagName} = true;
            }}
        }}

        public void Unset{propName}()
        {{
            {fieldName} = default;
            {flagName} = false;
        }}
    }}
}}";

            context.AddSource($"{className}_{propName}.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }
}
