nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: "https://artifactory.tools.saucelabs.net/artifactory/api/npm/all-npm"

npmRegistryServer: "https://artifactory.tools.saucelabs.net/artifactory/api/npm/all-npm"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

pnpMode: loose
