name: .NET (build)

on:
  push:
    branches:
      - main
    paths:
      - 'visual-dotnet/**'
      - .github/workflows/dotnet-build.yml
  pull_request:
    paths:
      - 'visual-dotnet/**'
      - .github/workflows/dotnet-build.yml

defaults:
  run:
    working-directory: visual-dotnet

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Install dotnet-format tool
        run: dotnet tool install -g dotnet-format
      - name: Restore dependencies
        run: dotnet restore
      - name: Run dotnet format
        run: dotnet format '.' --verify-no-changes
      - name: Build
        run: dotnet build .\SauceLabs.Visual\SauceLabs.Visual.csproj --no-restore
      - name: Test
        run: dotnet test --verbosity normal

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push to local registry
        uses: docker/build-push-action@v5
        with:
          context: '{{defaultContext}}:visual-dotnet'
          tags: saucelabs/visual-dotnet
          file: Dockerfile
          load: true
      - name: Run the integration tests
        run: |
          npm ci
          npm run test
        working-directory: tests
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          CONTAINER_IMAGE_NAME: saucelabs/visual-dotnet
