name: Espresso (Release)

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release type - major, minor or patch'
        required: true
        default: 'minor'
        options:
          - 'major'
          - 'minor'
          - 'patch'

defaults:
  run:
    working-directory: visual-espresso

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MVN_CENTRAL_USERNAME
          server-password: MVN_CENTRAL_PASSWORD

      - name: Setup Git
        if: ${{ steps.prep.outputs.tag_name == '' }}
        run: |
          git config --global user.name "sauce-visual-bot"
          git config --global user.email "visual@saucelabs.com"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build
        run: ./gradlew --no-daemon build

      - name: Bump version
        id: upgrade
        run: |
          ./gradlew --no-daemon -q bumpVersion -PreleaseType=${{ github.event.inputs.releaseType }}
          echo "version=$new_version" >> "$GITHUB_OUTPUT"

      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.MVN_CENTRAL_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.MVN_CENTRAL_GPG_PASSPHRASE }}

      - name: Release to Maven central
        run: |
          mvn -P release -Dgpg.passphrase="${{ secrets.MVN_CENTRAL_GPG_PASSPHRASE }}" \
              -Drevision=${{ steps.upgrade.outputs.version }} deploy
        env:
          MVN_CENTRAL_USERNAME: ${{ secrets.MVN_CENTRAL_USERNAME }}
          MVN_CENTRAL_PASSWORD: ${{ secrets.MVN_CENTRAL_PASSWORD }}

      - name: Push new version to Git
        id: push_to_git
        run: |
          tag_name="espresso-${{ steps.upgrade.outputs.version }}"
          git add ./visual/build.gradle
          git commit -m "[release] $tag_name"
          git tag $tag_name
          git push
          git push origin $tag_name

          echo "tag_name=$tag_name" >> "$GITHUB_OUTPUT"

      - name: Github Release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          tag_name: ${{ steps.push_to_git.outputs.tag_name }}
          files: visual-espresso/target/visual-release.aar
          generate_release_notes: true
