name: JS (release)

on:
  push:
    branches:
      - main
    paths:
      - 'visual-js/.changeset/**'

defaults:
  run:
    working-directory: visual-js

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org
      - name: Setup Git
        if: ${{ steps.prep.outputs.tag_name == '' }}
        run: |
          git config --global user.name "sauce-visual-bot"
          git config --global user.email "visual@saucelabs.com"
      - name: Build
        run: |
          corepack enable
          yarn install
          npx changeset status --output=changeset.json
          ./replace_pkg_version.sh changeset.json
          npm run build --workspaces --if-present
      - name: upgrade & publish version(s)
        run: |
          npx changeset version
          npx changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
      - name: Push to git
        run: git push --follow-tags
