name: JS (release)

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: visual-js

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org
      - name: Setup Git
        if: ${{ steps.prep.outputs.tag_name == '' }}
        run: |
          git config --global user.name "sauce-visual-bot"
          git config --global user.email "visual@saucelabs.com"
      - name: Build
        run: |
          corepack enable
          yarn install
          npm run build --workspaces --if-present
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          cwd: visual-js
          setupGitUser: false
          version: npx changeset version
          publish: npx changeset publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
