name: Python (build)

on:
  push:
    branches:
      - main
    paths:
      - 'visual-python/**'
      - .github/workflows/python-build.yml
  pull_request:
    paths:
      - 'visual-python/**'
      - .github/workflows/python-build.yml

defaults:
  run:
    working-directory: visual-python

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python build utilities
        run: pip install -r requirements/dev.txt
      - name: Build
        run: python -m build
      - name: Test
        run: python -m pytest

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push to local registry
        uses: docker/build-push-action@v5
        with:
          context: '{{defaultContext}}:visual-python'
          tags: saucelabs/visual-python
          file: Dockerfile
          load: true
      - name: Run the integration tests
        run: |
          npm ci
          npm run test
        working-directory: tests
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          CONTAINER_IMAGE_NAME: saucelabs/visual-python
