name: Python (build)

on:
  push:
    branches:
      - main
    paths:
      - 'visual-python/**'
  pull_request:
    paths:
      - 'visual-python/**'

defaults:
  run:
    working-directory: visual-python

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python build utilities
        run: pip install -r requirements/dev.txt
      - name: Build
        run: python -m build
      - name: Test
        run: python -m pytest
